"""datetime_in_planner

Revision ID: 20a5970dbf23
Revises: 22dbfbf4cc33
Create Date: 2025-02-01 19:58:53.383027

"""
from alembic import op
import sqlalchemy as sa

import app.helpers.db_set_type
# revision identifiers, used by Alembic.
revision = '20a5970dbf23'
down_revision = '22dbfbf4cc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('planner_feature', sa.Boolean(), nullable=False),
    sa.Column('expenses_feature', sa.Boolean(), nullable=False),
    sa.Column('view_ordering', app.helpers.db_list_type.DbListType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photo'], ['file.filename'], name=op.f('fk_household_photo_file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household'))
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('default_key', sa.String(length=128), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_category_household_id_household')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_household_id'), ['household_id'], unique=False)

    op.create_table('expense_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('color', sa.BigInteger(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_expense_category_household_id_household')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_category'))
    )
    op.create_table('household_member',
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('expense_balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_household_member_household_id_household')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_household_member_user_id_user')),
    sa.PrimaryKeyConstraint('household_id', 'user_id', name=op.f('pk_household_member'))
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('cook_time', sa.Integer(), nullable=True),
    sa.Column('prep_time', sa.Integer(), nullable=True),
    sa.Column('yields', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('suggestion_score', sa.Integer(), server_default='0', nullable=True),
    sa.Column('suggestion_rank', sa.Integer(), server_default='0', nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_recipe_household_id_household')),
    sa.ForeignKeyConstraint(['photo'], ['file.filename'], name=op.f('fk_recipe_photo_file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe'))
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_household_id'), ['household_id'], unique=False)

    op.create_table('shoppinglist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_shoppinglist_household_id_household')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shoppinglist'))
    )
    with op.batch_alter_table('shoppinglist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shoppinglist_household_id'), ['household_id'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_tag_household_id_household')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag'))
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('paid_by_id', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('exclude_from_statistics', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], name=op.f('fk_expense_category_id_expense_category')),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_expense_household_id_household')),
    sa.ForeignKeyConstraint(['paid_by_id'], ['user.id'], name=op.f('fk_expense_paid_by_id_user')),
    sa.ForeignKeyConstraint(['photo'], ['file.filename'], name=op.f('fk_expense_photo_file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense'))
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_household_id'), ['household_id'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('default_key', sa.String(length=128), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('ordering', sa.Integer(), server_default='0', nullable=True),
    sa.Column('support', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_item_category_id_category')),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_item_household_id_household')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_household_id'), ['household_id'], unique=False)

    op.create_table('planner',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yields', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_planner_household_id_household')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_planner_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('recipe_id', 'datetime', name=op.f('pk_planner'))
    )
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planner_household_id'), ['household_id'], unique=False)

    op.create_table('recipe_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ADDED', 'DROPPED', name='status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_recipe_history_household_id_household')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_history_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_history'))
    )
    op.create_table('recipe_tags',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_tags_recipe_id_recipe')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_recipe_tags_tag_id_tag')),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id', name=op.f('pk_recipe_tags'))
    )
    op.create_table('association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('antecedent_id', sa.Integer(), nullable=True),
    sa.Column('consequent_id', sa.Integer(), nullable=True),
    sa.Column('support', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('lift', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['antecedent_id'], ['item.id'], name=op.f('fk_association_antecedent_id_item')),
    sa.ForeignKeyConstraint(['consequent_id'], ['item.id'], name=op.f('fk_association_consequent_id_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_association'))
    )
    op.create_table('expense_paid_for',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name=op.f('fk_expense_paid_for_expense_id_expense')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_expense_paid_for_user_id_user')),
    sa.PrimaryKeyConstraint('expense_id', 'user_id', name=op.f('pk_expense_paid_for'))
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shoppinglist_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ADDED', 'DROPPED', name='status'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_history_item_id_item')),
    sa.ForeignKeyConstraint(['shoppinglist_id'], ['shoppinglist.id'], name=op.f('fk_history_shoppinglist_id_shoppinglist')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_history'))
    )
    op.create_table('recipe_items',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_recipe_items_item_id_item')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_items_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('recipe_id', 'item_id', name=op.f('pk_recipe_items'))
    )
    op.create_table('shoppinglist_items',
    sa.Column('shoppinglist_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_shoppinglist_items_created_by_user')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_shoppinglist_items_item_id_item')),
    sa.ForeignKeyConstraint(['shoppinglist_id'], ['shoppinglist.id'], name=op.f('fk_shoppinglist_items_shoppinglist_id_shoppinglist')),
    sa.PrimaryKeyConstraint('shoppinglist_id', 'item_id', name=op.f('pk_shoppinglist_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppinglist_items')
    op.drop_table('recipe_items')
    op.drop_table('history')
    op.drop_table('expense_paid_for')
    op.drop_table('association')
    op.drop_table('recipe_tags')
    op.drop_table('recipe_history')
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planner_household_id'))

    op.drop_table('planner')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_household_id'))

    op.drop_table('item')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_household_id'))

    op.drop_table('expense')
    op.drop_table('tag')
    with op.batch_alter_table('shoppinglist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shoppinglist_household_id'))

    op.drop_table('shoppinglist')
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_household_id'))

    op.drop_table('recipe')
    op.drop_table('household_member')
    op.drop_table('expense_category')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_household_id'))

    op.drop_table('category')
    op.drop_table('household')
    # ### end Alembic commands ###
